FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libsqlite3-dev \
    zip \
    unzip \
    nodejs \
    npm

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd


# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www

# Copy project files
COPY . .

# Copy custom php.ini
COPY php.ini /usr/local/etc/php/

# Install composer dependencies
RUN composer install

# Set ownership of the vendor directory
RUN chown -R www-data:www-data /var/www


# Install composer dependencies
RUN composer install

# Copy .env file
RUN cp .env.example .env

RUN mv vite.config.js vite.config.mjs

# Generate application key
RUN php artisan key:generate

# Run migrations
RUN php artisan migrate --force

# Install npm dependencies and build assets
RUN npm install && npm run build

# Set permissions
RUN chown -R www-data:www-data \
    /var/www/storage \
    /var/www/bootstrap/cache \
    /var/www/database

# Expose port 8000 (Laravel default)
EXPOSE 8000

# Start Laravel development server
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
