apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel-app
          image: laravel:latest # Replace with your image name and tag
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
#          env:
#            - name: APP_ENV
#              value: production
#            - name: APP_KEY
#              value: base64:your-app-key # Replace with your actual app key
#            - name: DB_CONNECTION
#              value: sqlite
#            - name: DB_HOST
#              value:
#            - name: DB_PORT
#              value: "3306"
#            - name: DB_DATABASE
#              value: laravel
#            - name: DB_USERNAME
#              value: root
#            - name: DB_PASSWORD
#              value: your-password # Replace with your actual DB password

