apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel-app
          image: laravel-app:latest # Replace with your image name and tag
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-app-service
  labels:
    app: laravel-app
spec:
  selector:
    app: laravel-app
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
